### ISSUE TITLE
Portability of the Code (Feature Confirmation)

### ISSUE THREAD

**Issue by MJunaidAhmad** [osman-mian/NeuralNetwork#1]
A.o.A Osman,

I want to use NN in my android application.  
Can I directly use your code in my application or you have used some library that is not available in android ?
Thanks in advance.

Regards,
Junaid

**Comment by osman-mian** [comment]
It should, you will need the Apache common math library files (available as jars in this code) since that is one of the dependencies of this :)

Cheers

**Comment by MJunaidAhmad** [comment]
perfect. Thanks again :D
